### ISSUE TITLE
lib/bencode/decoder.ex:56: type '*'(_,_) undefined

### ISSUE THREAD

**Issue by ericls** [gausby/bencode#6]
> $ mix compile 
> ==> bencode
> Compiling 5 files (.ex)
> warning: variable error is unused
>   lib/bencode/decoder.ex:61
> 
> == Compilation error on file lib/bencode/decoder.ex ==
> *\* (CompileError) lib/bencode/decoder.ex:56: type '*'(_,_) undefined
>     (stdlib) lists.erl:1338: :lists.foreach/2
>     (stdlib) erl_eval.erl:670: :erl_eval.do_apply/6

**Comment by gausby** [comment]
Thanks for reporting!

Fixed in v0.3.2
